# Generated by Django 5.2.4 on 2025-07-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product\\defualt_product.png', upload_to='product/'),
        ),
    ]
