# Generated by Django 5.2.4 on 2025-07-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='defualt_product.png', upload_to='product/'),
        ),
    ]
