# Generated by Django 5.2.4 on 2025-07-10 17:02

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=product.models.get_default_product_image, upload_to='product/'),
        ),
    ]
