# Generated by Django 5.2.4 on 2025-07-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_payment_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='trackung_code',
            new_name='tracking_code',
        ),
    ]
