# Generated by Django 5.2.4 on 2025-07-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='media\\profile\\prof_img.jpg', max_length=255, null=True, upload_to='profile'),
        ),
    ]
